services:
  erm-app:
    image: edgeforge/erm
    container_name: erm
    depends_on:
      - db
    ports:
      - "8080:8080" # Maps the container's port 8080 to the host's port 8080
#    environment:
#      - GIN_MODE=release # Add any necessary environment variables here
    networks:
      - erm_network
    restart: unless-stopped

  db:
    image: postgres:17-alpine3.20
    container_name: db
    environment:
      POSTGRES_USER: erm_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: erm_database
    ports:
      - "5432:5432" # Maps the container's port 5432 to the host's port 5432
    networks:
      - erm_network
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  erm_network:
    driver: bridge

volumes:
  db_data: