# TODO: Create a release on GitHub with the binary attached, Gitversion will automatically update the version number, Build stage, Release stage


# 1. Checkout code
# 2. Call our custom `GitVersion action` to tag the repo
# 3. Compile the Go code
# 4. Sign the package,
# 4. use go releaser
# 5. Create release for binary

# Azure pipelines example.
# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

